spring:
  application:
    name: ranking-service
  datasource:
    url: jdbc:postgresql://localhost:5434/ranking
    username: postgres
    password: ranking123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      enabled: false
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always